config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('tempo.users.urls', namespace='users')),
    url(r'^events/', include('tempo.events.urls', namespace='events')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/', include('config.api_urls', namespace='api')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

tempo/events/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include

from . import views

events_patterns = [
    url(
        regex=r'^create$',
        view=views.EventCreate.as_view(),
        name='create'
    ),
]
entries_patterns = [
    url(
        regex=r'^create$',
        view=views.EntryCreate.as_view(),
        name='create'
    ),
]
urlpatterns = [
    url(
        r'^timeline$',
        view=views.Log.as_view(),
        name='timeline'
    ),
    url(
        r'^events/',
        include(events_patterns, namespace='events'),
    ),
    url(
        r'^entries/',
        include(entries_patterns, namespace='entries'),
    ),
]

tempo/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

tempo/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
import pytz


from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    TZ_CHOICES = [(x, x) for x in pytz.common_timezones]
    timezone = models.CharField(
        choices=TZ_CHOICES, default=settings.TIME_ZONE, max_length=100)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tempo/events/forms.py
import datetime
from django import forms
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from . import models


class EventCreateForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = (
            'verbose_name',
            'description',
        )


class EntryCreateForm(forms.ModelForm):
    class Meta:
        model = models.Entry
        fields = (
            'config',
            'comment',
            'detail_url',
            'is_public',
        )


class ByDayForm(forms.Form):
    start = forms.DateField(required=False)
    end = forms.DateField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get('start')
        end = cleaned_data.get('end')
        if not start and not end:
            cleaned_data['end'] = timezone.now().date()
            cleaned_data['start'] = cleaned_data['end'] - datetime.timedelta(days=15)
        try:
            if cleaned_data['start'] >= cleaned_data['end']:
                raise forms.ValidationError('End must be greater than start')
        except (KeyError, TypeError):
            pass


class EntrySuggestionForm(forms.Form):
    date = forms.DateTimeField(required=False)


class StatsForm(forms.Form):
    start = forms.DateField(required=False)
    end = forms.DateField(required=False)
    fill = forms.BooleanField(required=False)

    ORDERING_CHOICES = [
        ('date', _('Ascending')),
        ('-date', _('Descending')),
    ]
    ordering = forms.ChoiceField(choices=ORDERING_CHOICES, required=False)

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get('start')
        end = cleaned_data.get('end')
        if not start and not end:
            cleaned_data['end'] = timezone.now().date()
            cleaned_data['start'] = cleaned_data['end'] - datetime.timedelta(days=15)
        try:
            if cleaned_data['start'] >= cleaned_data['end']:
                raise forms.ValidationError('End must be greater than start')
        except (KeyError, TypeError):
            pass

tempo/events/views.py
import itertools
import datetime
import slugify

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import urlresolvers, paginator
from django import http
from django.db.models import Q
from django.utils import timezone

from taggit.models import Tag

from rest_framework import viewsets
from rest_framework import mixins
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.decorators import detail_route, list_route

from . import forms
from . import models
from . import serializers
from . import filters
from . import suggestions


class Log(LoginRequiredMixin, generic.TemplateView):
    template_name = 'events/log.html'


class EventCreate(LoginRequiredMixin, generic.CreateView):
    form_class = forms.EventCreateForm
    template_name = 'events/events/create.html'
    success_url = urlresolvers.reverse_lazy('home')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        r = super().form_valid(form)
        form.instance.configs.create(
            user=self.request.user)
        return r


class EntryCreate(LoginRequiredMixin, generic.TemplateView):
    template_name = 'events/entries/create.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['Entry'] = models.Entry
        return context


class Search(APIView):

    config = {
        'config': {
            'qs': models.EventConfig.objects.select_related('event'),
            'user_attr': 'user',
            'search_fields': ['event__verbose_name'],
            'title_field': 'title',
        }
    }

    def get(self, request, format=None):
        t = request.GET['type']
        query = request.GET['q']
        results = self.get_results(request, t, query)
        return Response({'results': self.serialize_results(results)})

    def get_results(self, request, t, query):
        conf = self.config[t]
        lookups = {
            '{}'.format(conf['user_attr']): request.user,
        }
        q = None
        for f in conf['search_fields']:
            _q = Q(**{'{}__icontains'.format(f): query})
            if not q:
                q = _q
            else:
                q |= _q

        return conf['qs'].filter(**lookups).filter(q)

    def serialize_results(self, qs):
        return [
            {'value': i.pk, 'name': i.title, 'text': i.title}
            for i in qs
        ]


class EntryViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.EntrySerializer
    lookup_field = 'uuid'
    lookup_value_regex = '[0-9a-f-]{36}'

    def get_queryset(self):
        return models.Entry.objects.filter(
            config__user=self.request.user
        ).select_related('config__event').prefetch_related('tags')

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)

        if getattr(instance, '_prefetched_objects_cache', None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        return Response(serializers.EntryNestedSerializer(instance).data)

    @list_route(methods=['GET'])
    def byday(self, request, *args, **kwargs):
        qs = self.get_queryset()
        form = forms.ByDayForm(request.GET)
        if not form.is_valid():
            return Response({'errors': form.errors.as_json()}, status=400)

        qs = filters.EntryFilter(request.GET, queryset=qs).qs

        data = {
            'start': form.cleaned_data['start'],
            'end': form.cleaned_data['end'],
            'days': qs.by_day(
                end=form.cleaned_data['end'],
                start=form.cleaned_data['start'],
                fill=False,
                serializer_class=serializers.EntryNestedSerializer,
            ),
        }
        return Response(data, status=200)

    @list_route(methods=['GET'])
    def suggestions(self, request, *args, **kwargs):
        form = forms.EntrySuggestionForm(request.GET)
        if not form.is_valid():
            return Response({'errors': form.errors.as_json()}, status=400)

        qs = self.get_queryset()
        ref = form.cleaned_data.get('date') or timezone.now()
        results = suggestions.rank_by_closest(qs, 'start', ref)

        results = [
            {
                'score': score,
                'entry': serializers.EntryNestedSerializer(entry).data}
            for score, entry in results
        ][:10]
        return Response(results, status=200)

    @list_route(methods=['GET'])
    def stats(self, request, *args, **kwargs):
        qs = self.get_queryset()
        initial = {
            'start': timezone.now().date(),
            'end': (timezone.now() - datetime.timedelta(days=14)).date(),
            'fill': True,
            'ordering': 'date',
        }
        form = forms.StatsForm(request.GET, initial=initial)
        if not form.is_valid():
            return Response({'errors': form.errors.as_json()}, status=400)

        data = {
            'fill': form.cleaned_data['fill'] or initial['fill'],
            'start': form.cleaned_data['start'] or initial['start'],
            'end': form.cleaned_data['end'] or initial['end'],
            'ordering': form.cleaned_data['ordering'] or initial['ordering'],
        }
        data['results'] = qs.stats(
            'day',
            **data
        )

        return Response(data, status=200)


class TagViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
    serializer_class = serializers.TagSerializer

    def get_queryset(self):
        return Tag.objects.all()

    @list_route(methods=['get'])
    def search(self, request, pk=None):
        qs = self.get_queryset().filter(
            slug__icontains=request.GET.get('q', ''))
        serializer = self.serializer_class(qs, many=True)
        return Response({"results": serializer.data},
                        status=200)


class ConfigViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.ConfigSerializer

    def get_queryset(self):
        return self.request.user.event_configs.all()

    def create(self, request, *args, **kwargs):
        serializer = serializers.EventSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        try:
            slug = slugify.Slugify(
                to_lower=True,
                max_length=190,
            )(serializer.validated_data['verbose_name'])
            event = models.Event.objects.get(slug=slug)
        except models.Event.DoesNotExist:
            self.perform_create(serializer)
            event = serializer.instance
            event.created_by = request.user
            event.save()

        config, _ = models.EventConfig.objects.get_or_create(
            event=event,
            user=request.user
        )
        serializer = self.get_serializer(instance=config)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

tempo/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

tempo/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

tempo/templates/base.html
{% load staticfiles i18n compress sekizai_tags %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}tempo{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    {% render_block "css" postprocessor "compressor.contrib.sekizai.compress" %}
    {% addtoblock "css" %}
      <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
      <link rel="stylesheet" href="{% static 'semantic/dist/semantic.min.css' %}" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'vendor/calendar.min.css' %}" crossorigin="anonymous">
    {% endaddtoblock %}

  </head>

  <body class="pushable">
      <div class="pusher">
        {% include 'main_navigation.html' %}

        <div class="ui vertical">
            <div class="ui text container">
              {% if messages %}
                  {% for message in messages %}
                      <div class="ui message alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
                  {% endfor %}
              {% endif %}
            </div>
        </div>
        <div id="content">
          {% block content %}{% endblock content %}
        </div>
        {% block modal %}{% endblock modal %}
        <div class="ui hidden divider"></div>
        <div class="ui inverted vertical footer segment">
          <div class="ui four columns center aligned grid">
            <div class="column">
              <h4>{% trans 'Links' %}</h4>
              <div class="ui inverted link list">
                <a class="item" href="{% url 'about' %}">{% trans 'About' %}</a>
                <a class="item" href="https://github.com/EliotBerriot/tempo">{% trans 'Contribute to Tempo' %}</a>
              </div>
            </div>
          </div>
        </div>
    </div>
    {% if js_dsn %}
        <script src="{% static 'vendor/raven.min.js' %}" crossorigin="anonymous"></script>
        <script>
          Raven.config('{{ js_dsn }}').install()
        </script>
    {% endif %}
    <script>

      var CONFIG = {}
      {% if request.user.is_authenticated %}
      CONFIG.timezone = "{{ request.user.timezone}}"
      {% else %}
      CONFIG.timezone = "{{ default_timezone }}"
      {% endif %}

      function getParameterByName(name, url) {
          if (!url) {
            url = window.location.href;
          }
          name = name.replace(/[\[\]]/g, "\\$&");
          var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
              results = regex.exec(url);
          if (!results) return null;
          if (!results[2]) return '';
          return decodeURIComponent(results[2].replace(/\+/g, " "));
      };

    </script>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% render_block "js_files" postprocessor "compressor.contrib.sekizai.compress" %}
    {% render_block "js_scripts" postprocessor "compressor.contrib.sekizai.compress" %}
    {% addtoblock "js_files" %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="{% static 'vendor/jquery.min.js' %}" crossorigin="anonymous"></script>
      <script src="{% static 'semantic/dist/semantic.min.js' %}" crossorigin="anonymous"></script>
      <script src="{% static 'vendor/calendar.min.js' %}" crossorigin="anonymous"></script>
      <script src="{% static 'vendor/vue.js' %}" crossorigin="anonymous"></script>
    {% endaddtoblock %}
    {% addtoblock "js_scripts" %}
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script>
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
      function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
        });
      </script>
    {% endaddtoblock %}
  </body>
</html>

tempo/templates/main_navigation.html
{% load i18n %}
<div class="ui large top menu">
    <nav class="ui container">
      <a class="item" href="{% url 'home' %}">Tempo</a>


      <div class="right menu">
        {% if request.user.is_authenticated %}
            <a class="item" href="{% url 'events:entries:create' %}">{% trans "Add entry" %}</a>
            <a class="item" href="{% url 'events:timeline' %}">{% trans "Timeline" %}</a>
            <a class="item" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
            <a class="item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
        {% else %}
            <a id="sign-up-link" class="item" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            <a id="log-in-link" class="item" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
        {% endif %}
      </div>
    </nav>
</div>